language: python
addons:
  postgresql: "9.5"
python:
- '2.7'
before_install:
- sudo apt-get install libarchive-zip-perl
- psql -c 'create database freesound;' -U postgres
- cp freesound/local_settings.example.py freesound/local_settings.py
- cp freesound/logger.example.py freesound/logger.py
- cp similarity/similarity_settings.example.py similarity/similarity_settings.py
- cp tagrecommendation/tagrecommendation_settings.example.py tagrecommendation/tagrecommendation_settings.py
- sed -i 's$/path/to/django/debug.log$debug.log$' freesound/logger.py
- sed -i 's$^DISPLAY_DEBUG_TOOLBAR.*$DISPLAY_DEBUG_TOOLBAR = False$' freesound/local_settings.py
- mkdir -p ../freesound-data/packs
- mkdir -p ../freesound-data/uploads
- mkdir -p ../freesound-data/avatars
install:
- pip install -U pip
- pip install django-nose
- pip install -r requirements.txt
script:
- python manage.py test --noinput --settings=freesound.test_settings follow accounts apiv2 tickets support utils sounds ratings search forum
notifications:
  hipchat:
    rooms:
      secure: Ve8Xt4Y+lhhnuyJQbp7u7RyzjMs/7U97fAM+lh/FtEEhQrR8DmxA75dXoy4yS1wvijY8Ob/AQEAtbU1LRdaqPUNetu+KL2ip6mTlb+BIGK3EzZh8iCXVZRZFjkEs9uLsUFYS38GdmALvUtYRKCXsATvvznvp22z3x0FRkGkL+b4=
